version: '3.8'

services:
  wellness-assistant:
    build: .
    ports:
      - "80:5000"
    volumes:
      - wellness_data:/app/data
      - wellness_exports:/app/exports
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
      - PORT=5000
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "8080:80"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - wellness-assistant
    restart: always
    deploy:
      resources:
        limits:
          memory: 128M

volumes:
  wellness_data:
    driver: local
  wellness_exports:
    driver: local

networks:
  default:
    driver: bridge
